# Generated by Django 4.1.2 on 2022-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('address', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('I', 'Include powerfull turbocharge')], max_length=250, verbose_name='статус')),
            ],
        ),
        migrations.CreateModel(
            name='Warehause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vw_deutchland', models.CharField(max_length=250)),
                ('audi_deutchland', models.CharField(max_length=250)),
                ('auto_market_malinovka', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='engine',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
