# Generated by Django 4.1.2 on 2022-10-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_buyer_condition_warehause_auto_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='warehause',
            field=models.ManyToManyField(to='api.warehause'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.warehause'),
        ),
        migrations.AddField(
            model_name='condition',
            name='auto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.auto'),
        ),
    ]
