# Generated by Django 4.1.2 on 2022-10-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_warehouse_remove_auto_warehause_auto_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='type_warehouse',
            field=models.CharField(choices=[('Official_dealer', 'Official_dealer'), ('M', 'Market_auto_used'), ('P', 'Перекуп')], max_length=250),
        ),
    ]
