# Generated by Django 4.1.2 on 2022-10-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_warehouse_type_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='type_warehouse',
            field=models.CharField(choices=[('Official_dealer', 'Official_dealer'), ('Market_auto_used', 'Market_auto_used'), ('Перекуп', 'Перекуп')], max_length=250),
        ),
    ]
