# Generated by Django 4.1.2 on 2022-10-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_condition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
