# Generated by Django 4.1.2 on 2022-10-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_buyer_warehouse_warehouse_buyers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='buyers',
        ),
        migrations.AddField(
            model_name='buyer',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
    ]
