# Generated by Django 4.1.2 on 2022-11-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_warehouse_type_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='warehouse',
            field=models.ManyToManyField(related_name='autos', to='api.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='type_warehouse',
            field=models.CharField(choices=[('Official_dealer', 'Official_dealer'), ('Market_auto_used', 'Market_auto_used'), ('Перекуп', 'Перекуп')], max_length=250),
        ),
    ]
