# Generated by Django 4.1.2 on 2022-11-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_auto_warehouse_alter_warehouse_type_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
