# Generated by Django 4.1.2 on 2022-11-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_airboard_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='airboard',
        ),
        migrations.AddField(
            model_name='airport',
            name='airboard',
            field=models.ManyToManyField(to='api.airboard'),
        ),
    ]
