# Generated by Django 4.1.2 on 2022-11-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_house_person_person_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='airboard',
        ),
        migrations.AddField(
            model_name='airport',
            name='airboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.airboard'),
            preserve_default=False,
        ),
    ]
