# Generated by Django 4.1.2 on 2022-11-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_airport_airboard_airport_airboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='airboard',
        ),
        migrations.AddField(
            model_name='airport',
            name='airboard',
            field=models.ManyToManyField(to='api.airboard'),
        ),
    ]
